# Generated by Django 5.1.7 on 2025-05-16 19:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learnai_app', '0003_quizresult_quizanswer'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='generatedcontent',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='generatedcontent',
            name='content_type',
            field=models.CharField(choices=[('summary', 'Summary'), ('notes', 'Study Notes'), ('flashcards', 'Flashcards'), ('quiz', 'Quiz')], max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='generatedcontent',
            unique_together={('user', 'material', 'content_type')},
        ),
    ]
