# Generated by Django 5.1.7 on 2025-05-17 00:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learnai_app', '0004_generatedcontent_updated_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quizresult',
            options={'ordering': ['-completed_at']},
        ),
        migrations.AddField(
            model_name='quizresult',
            name='completed',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterUniqueTogether(
            name='quizresult',
            unique_together={('user', 'quiz')},
        ),
    ]
